// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "Pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary* wrapResult(NSDictionary *result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = [NSDictionary dictionaryWithObjectsAndKeys:
        (error.code ? error.code : [NSNull null]), @"code",
        (error.message ? error.message : [NSNull null]), @"message",
        (error.details ? error.details : [NSNull null]), @"details",
        nil];
  }
  return [NSDictionary dictionaryWithObjectsAndKeys:
      (result ? result : [NSNull null]), @"result",
      errorDict, @"error",
      nil];
}

@interface FLTAddReply ()
+(FLTAddReply*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end
@interface FLTAddRequest ()
+(FLTAddRequest*)fromMap:(NSDictionary*)dict;
-(NSDictionary*)toMap;
@end

@implementation FLTAddReply
+(FLTAddReply*)fromMap:(NSDictionary*)dict {
  FLTAddReply* result = [[FLTAddReply alloc] init];
  result.result = dict[@"result"];
  if ((NSNull *)result.result == [NSNull null]) {
    result.result = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.result ? self.result : [NSNull null]), @"result", nil];
}
@end

@implementation FLTAddRequest
+(FLTAddRequest*)fromMap:(NSDictionary*)dict {
  FLTAddRequest* result = [[FLTAddRequest alloc] init];
  result.n1 = dict[@"n1"];
  if ((NSNull *)result.n1 == [NSNull null]) {
    result.n1 = nil;
  }
  result.n2 = dict[@"n2"];
  if ((NSNull *)result.n2 == [NSNull null]) {
    result.n2 = nil;
  }
  return result;
}
-(NSDictionary*)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.n1 ? self.n1 : [NSNull null]), @"n1", (self.n2 ? self.n2 : [NSNull null]), @"n2", nil];
}
@end

void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi> api) {
  {
    FlutterBasicMessageChannel *channel =
      [FlutterBasicMessageChannel
        messageChannelWithName:@"dev.flutter.pigeon.Api.add"
        binaryMessenger:binaryMessenger];
    if (api) {
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        FlutterError *error;
        FLTAddRequest *input = [FLTAddRequest fromMap:message];
        FLTAddReply *output = [api add:input error:&error];
        callback(wrapResult([output toMap], error));
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
