// Autogenerated from Pigeon (v0.1.4), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class FLTAddReply;
@class FLTAddRequest;

@interface FLTAddReply : NSObject
@property(nonatomic, strong, nullable) NSNumber * result;
@end

@interface FLTAddRequest : NSObject
@property(nonatomic, strong, nullable) NSNumber * n1;
@property(nonatomic, strong, nullable) NSNumber * n2;
@end

@protocol FLTApi
-(nullable FLTAddReply *)add:(FLTAddRequest*)input error:(FlutterError *_Nullable *_Nonnull)error;
@end

extern void FLTApiSetup(id<FlutterBinaryMessenger> binaryMessenger, id<FLTApi> _Nullable api);

NS_ASSUME_NONNULL_END
