import 'package:flutter/material.dart';

import './api_generated.dart';

class Home extends StatelessWidget {
  void callNativeAdd() async {
    // `Api` is a class generated by Pigeon
    final api = Api();
    final req = AddRequest()
      ..n1 = 10
      ..n2 = 20;
    final reply = await api.add(req);
    print(reply.result); // prints 30
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      body: Center(
        child: RaisedButton(
          child: Text("call native add method"),
          onPressed: () => callNativeAdd(),
        ),
      ),
    );
  }
}
